navbar:
  blog_title: '共识边缘'   # 在单引号里写上你想要的名字

# ====== 主页打字机标语配置 ======
index:
  slogan:
    enable: true
    text: '技术世界的观察者与践行者'   # 把这里的文字替换成你想要的任何中文标语
  
post:
  comments:
    enable: true
    type: giscus

giscus:
  repo: 'evenader/evenader.github.io'
  repo-id: 'R_kgDORk4-aw'
  category: 'Announcements'
  category-id: 'DIC_kwDORk4-a84C4Nml'
  mapping: 'pathname'
  strict: 0
  reactions-enabled: 1
  emit-metadata: 0
  input-position: 'bottom'
  theme-light: 'light'
  theme-dark: 'dark'
  lang: 'zh-CN'
  crossorigin: 'anonymous'
